site_name: Documentação Angular 16 e Node.js
nav:
  - Home: index.md
  - Introdução:
      - Visão Geral: introducao/visao_geral.md
      - Configuração do Ambiente: introducao/configuracao_ambiente.md
  - Angular:
      - Conceitos Básicos: angular/conceitos_basicos.md
      - Componentes: angular/componentes.md
      - Diretivas: angular/diretivas.md
      - Serviços e Injeção de Dependência: angular/servicos_injecao_dependencia.md
  - Node.js:
      - Introdução ao Node.js: nodejs/introducao.md
      - Gerenciamento de Pacotes (npm): nodejs/npm.md
      - Express.js: nodejs/express.md
      - Comunicação com Banco de Dados: nodejs/comunicacao_banco.md
theme:
  name: 'material'
